#!/bin/bash
#
# mactab_to_configfiles
# Copyright (c) 2006 Dell, Inc.
#  by Matt Domsch <Matt_Domsch@dell.com>
#  Dual-licensed under the GNU GPL v2 or later
#  or the Mozilla Public License v1.1 or later
#
# This program takes a list of ethernet device names,
# MAC addresses, and driver names, and sets the
# /etc/sysconfig/network-scripts/ifcfg-$name HWADDR fields to match.
# It also changes the order of the drivers listed in /etc/modprobe.conf
# to match.

let i=0
while read eth mac comment driver; do
      ETH_NAME[${i}]=${eth}
      ETH_MAC[${i}]=`echo ${mac} | awk '{print toupper($1)}'`
      ETH_DRIVER[${i}]=${driver}
      i=$((i+1))
done

tmp_file=`mktemp /tmp/mactab_to_configfiles.XXXXXX`
trap "rm -f $tmp_file" QUIT TERM INT HUP EXIT

let i=0
while [ ${i} -lt ${#ETH_NAME[@]} ]; do
    CFG=/etc/sysconfig/network-scripts/ifcfg-${ETH_NAME[${i}]}
    if [ ! -f ${CFG} ]; then
        echo "DEVICE=${ETH_NAME[${i}]}" >> ${CFG}
        echo "ONBOOT=yes" >> ${CFG}
    fi
    if [ -f ${CFG} ]; then
	EXISTING_MAC=`grep ^HWADDR ${CFG} | awk -F= '{print toupper($2)}'`
	if [ -n "${EXISTING_MAC}" ]; then
	    if [ "${EXISTING_MAC}" != "${ETH_MAC[${i}]}" ]; then
		echo "Changing $CFG HWADDR from ${EXISTING_MAC} to ${ETH_MAC[${i}]}"
		sed -e "s/HWADDR=.*/HWADDR=${ETH_MAC[${i}]}/" ${CFG} > ${tmp_file}
		mv -f ${tmp_file} ${CFG}
	    fi
	else
	    echo "Adding $CFG HWADDR ${ETH_MAC[${i}]}"
	    echo "HWADDR=${ETH_MAC[${i}]}" >> ${CFG}
	fi
    fi
    i=$((i+1))
done

. ./edit_modprobe_conf

rm -f ${tmp_file}
