#!/bin/bash
#
# mactab_to_sles9_configfiles
# Copyright (c) 2006 Dell, Inc.
#  by Matt Domsch <Matt_Domsch@dell.com>
#  Dual-licensed under the GNU GPL v2 or later
#  or the Mozilla Public License v1.1 or later
#
# This program takes a list of ethernet device names,
# MAC addresses, and driver names, and sets the
# /etc/sysconfig/network/ifcfg-eth-id-$mac PERSISTENT_NAME fields to match.

let i=0
while read eth mac comment driver; do
      ETH_NAME[${i}]=${eth}
      ETH_MAC[${i}]=`echo ${mac} | awk '{print toupper($1)}'`
      ETH_MAC_LC[${i}]=`echo ${mac} | awk '{print tolower($1)}'`
      ETH_DRIVER[${i}]=${driver}
      i=$((i+1))
done

tmpdir=`mktemp -d /tmp/mactab_to_configfiles.XXXXXX`
trap "rm -rf $tmpdir" QUIT TERM INT HUP EXIT

let i=0
while [ ${i} -lt ${#ETH_NAME[@]} ]; do
    CFG=/etc/sysconfig/network/ifcfg-eth-id-${ETH_MAC_LC[${i}]}
    if [ -e $CFG ]; then
	unset PERSISTENT_NAME
	. $CFG
	if [ -n "${PERSISTENT_NAME}" ]; then
	    if [ "${PERSISTENT_NAME}" != "${ETH_NAME[${i}]}" ]; then
		echo "Changing $CFG PERSISTENT_NAME from ${PERSISTENT_NAME} to ${ETH_NAME[${i}]}"
		sed -e "s:PERSISTENT_NAME=.*:PERSISTENT_NAME=\'${ETH_NAME[${i}]}\':" $CFG > $tmpdir/`basename $CFG`
		mv $tmpdir/`basename $CFG` /etc/sysconfig/network
	    fi
	else
	    echo "Adding $CFG PERSISTENT_NAME ${ETH_NAME[${i}]}"
	    echo "PERSISTENT_NAME='${ETH_NAME[${i}]}'" >> ${CFG}
	fi
    fi
    i=$((i+1))
done

# Use our versions of ifup and friends
cd sles9
unset DIFF
DIFF=$(which diff)
for f in etc/sysconfig/network/scripts/functions.common \
    sbin/ifup sbin/rename_netiface ; do
  if [ -n "$DIFF" ] ; then
      $DIFF /$f $f > /dev/null 2>&1
      RC=$?
      if [ $RC -eq 1 ] ; then
	  echo "Replacing /$f with our copy."
	  cp $f /$f
	  chmod 755 /$f
      elif [ $RC -gt 1 ] ; then
	  echo "Installing /$f with our copy."
	  cp $f /$f
	  chmod 755 /$f
      fi
  else
      echo "Replacing /$f with our copy."
      cp $f /$f
      chmod 755 /$f
  fi
done
